export const UPDATE_COLOR = "UPDATE_COLOR";
export const UPDATE_MOUTING = "UPDATE_MOUTING";
export const UPDATE_CONTROL_PLACE = "UPDATE_CONTROL_PLACE";
export const UPDATE_SYSTEM_PARAMETER = "UPDATE_SYSTEM_PARAMETER";
export const UPDATE_SHAPE = "UPDATE_SHAPE";
export const UPDATE_SUSPENSION_TYPE = "UPDATE_SUSPENSION_TYPE";
export const UPDATE_SIDES = "UPDATE_SIDES";
export const UPDATE_LENGTH = "UPDATE_LENGTH";
