export const UPDATE_COLOR = "UPDATE_COLOR";
export const UPDATE_MOUTING = "UPDATE_MOUTING";
export const UPDATE_CONTROL_PLACE = "UPDATE_CONTROL_PLACE";
export const UPDATE_SYSTEM_PARAMETER = "UPDATE_SYSTEM_PARAMETER";
